### ISSUE TITLE
Can I have the source code?

### ISSUE THREAD

**Issue by tanc7** [trewisscotch/CobaltStr4.4#2]
So this release compared to the previous 4.0 crack now has a working CovertVPN. However, I do not have the options of having beacons communicate to one another outside of only TCP. I would like the source code leak if you can point me to it so I can recompile and customize Cobalt Strike to have working SMB beacon-to-beacon communications.

**Comment by trewisscotch** [comment]
> So this release compared to the previous 4.0 crack now has a working CovertVPN. However, I do not have the options of having beacons communicate to one another outside of only TCP. I would like the source code leak if you can point me to it so I can recompile and customize Cobalt Strike to have working SMB beacon-to-beacon communications.


Hello, write me telegram contact @trewisscotch

**Comment by tanc7** [comment]
Hey I can't find you on Telegram, can you email me at slayerranger@protonmail.com?
